name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  setup:
    name: 'Setup Environment'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.45.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  pmd-analysis:
    name: 'PMD Analysis'
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: mcr.microsoft.com/playwright/java:v1.45.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PMD Source Code Analysis
        run: mvn pmd:pmd

      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: target/site/pmd.html

  playwright-tests:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        browser: [ chromium, firefox, webkit ]
    container:
      image: mcr.microsoft.com/playwright/java:v1.45.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Playwright Tests
        run: mvn test -Dtestng.xml=path/to/your/testng.xml -Dbrowser=${{ matrix.browser }}
        env:
          HOME: /root
          ENVIRONMENT: development

      - name: Upload Surefire Test Report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-report-${{ matrix.browser }}
          path: target/surefire-reports
          if-no-files-found: warn
          retention-days: 7